### ISSUE TITLE
undefined symbol: wallTime

### ISSUE THREAD

**Issue by catketchup** [huffenberger-cosmology/lognormal_mocks#1]
Hello, when I import "lognormal_mocks_mod" in python, there is error of "undefined symbol: wallTime". I am wondering if you have any idea what may cause this? (maybe there is a library not included?) Thank you so much!

**Comment by huffenbe** [comment]
We have found that "wallTime" is provided by libsharp.  I have added that to the library dependencies in the setup.py file.
